---
- name: Config ELK VM with Docker
  hosts: 52.137.81.98
  remote_user: azShomari
  become: true
  tasks:
    - name: Install docker.io
      apt:
        force_apt_get: yes
        name: docker.io
        state: present
        update_cache: yes
    - name: Install pip3
      apt:
        name: python3-pip
        state: present
        force_apt_get: yes
    - name: Install docker via pip
      pip:
        name: docker
        state: present
    - name: Increase virtual memory
      command: sysctl -w vm.max_map_count=262144
    - name: Use more memory
      sysctl:
        name: vm.max_map_count
        value: '262144'
        state: present
        reload: yes
    - name: download and launch a docker elk container
      docker_container:
        name: elk
        image: sebp/elk:761
        state: started
        restart_policy: always
        # Please list the ports that ELK runs on
        published_ports:
          -  5601:5601
          -  9200:9200
          -  5044:5044
